name: Update and Run Application on Instance

on:
  push:
    branches:
      - dev  
  pull_request:
    branches:
      - dev  

jobs:
  update-and-run:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Attempt SSH Connection
        run: |
          echo "Attempting to SSH into: ${{ secrets.VM_USER }}@${{ 10.48.10.29 }}"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "${{ secrets.VM_USER }}@${{ 10.48.10.29 }}" "echo Connected Successfully!"

      - name: Pull Latest Changes and Manage Processes
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "${{ secrets.VM_USER }}@${{ 10.48.10.29 }}" << 'EOF'
            # Kill existing processes listening on ports 3000 to 3009
            PIDs=$(sudo netstat -tulnp | grep -E ':300[0-9]' | awk '{print $7}' | cut -d'/' -f1)
            if [ -n "$PIDs" ]; then
              echo "Killing processes with PIDs: $PIDs"
              sudo kill -9 $PIDs
            else
              echo "No processes found listening on ports 3000 to 3009"
            fi

            # Check the current branch and pull the latest code
            echo "Checking current branch..."
            CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
            echo "Current branch is: $CURRENT_BRANCH"
            if [ "$CURRENT_BRANCH" != "dev" ]; then
              echo "Switching to dev branch..."
              git checkout dev
            fi
            
            echo "Pulling latest code in /home/ec2-user/ai-avatar"
            cd /home/ec2-user/ai-avatar  
            git pull
            
            # Install dependencies and build the application
            echo "Starting npm install..."
            npm install
            echo "Building the application..."
            npm run build  
            
            # Start the application in a detached screen session
            echo "Starting the application in a detached screen session..."
            screen -dmS myapp npm run dev
          EOF
